### ISSUE TITLE
WARNING: It is not fully supported to define distributionSha256Sum in gradle-wrapper.properties. Using an incorrect value may freeze or crash Android Studio.

### ISSUE THREAD

**Issue by ahsaniqbal47** [SecUSo/privacy-friendly-ludo#14]
![issue](https://user-images.githubusercontent.com/59462763/75618910-71c24300-5b96-11ea-806a-fbb1c7df66ea.JPG)
Sir i got this warning in Android Studio how can i resolve this issue
WARNING: It is not fully supported to define distributionSha256Sum in gradle-wrapper.properties.
Using an incorrect value may freeze or crash Android Studio.
Please manually verify or remove this property from all of included projects if applicable.
For more details, see https://github.com/gradle/gradle/issues/9361.

Use "71a787..." as checksum for https://services.gradle.org/distributions/gradle-3.3-all.zip and sync project
Remove distributionSha256Sum and sync project
Open Gradle wrapper properties

**Comment by Kamuno** [comment]
You have to delete the 'distributionSha256Sum' in the gradle-wrapper.properties file. We added the checksum for the f-droid store, because it would always add a warning tag if we did not include it but android studio stopped supporting it.

On an old version of android studio, this would indeed lead to the IDE not opening. But this is no longer the case on the newer versions. If you still would like to use the checksum for whatever reason, you can find the correct checksums for every version here: https://gradle.org/release-checksums/

**Comment by Kamuno** [comment]
Just click the 2nd option and you are good to go ;)

**Comment by airon-main** [comment]
Just prepare the internet and time. the download take some time

**Comment by airon-main** [comment]
> Just click the 2nd option and you are good to go ;)

Just prepare the internet and time. the download took some time
